/**
 * Matriz de Permissões e Regras de Controle de Acesso Baseado em Papéis (RBAC)
 */

import { PerfilUsuario } from '../../../backend/src/types';

export const PERMISSOES = {
  // Produtor
  PRODUTOR_VER_PROPRIOS_DADOS: "PRODUTOR_VER_PROPRIOS_DADOS",
  PRODUTOR_SOLICITAR_REPASSE: "PRODUTOR_SOLICITAR_REPASSE",
  PRODUTOR_SOLICITAR_ANTECIPACAO: "PRODUTOR_SOLICITAR_ANTECIPACAO",
  PRODUTOR_TRANSFERIR_SALDOS: "PRODUTOR_TRANSFERIR_SALDOS",
  PRODUTOR_ASSINAR_DIGITALMENTE: "PRODUTOR_ASSINAR_DIGITALMENTE",

  // Financeiro Disk
  FINANCEIRO_VISAO_GLOBAL: "FINANCEIRO_VISAO_GLOBAL",
  FINANCEIRO_ANALISAR_OPERACAO: "FINANCEIRO_ANALISAR_OPERACAO",
  FINANCEIRO_APROVAR_REJEITAR: "FINANCEIRO_APROVAR_REJEITAR",
  FINANCEIRO_ASSINAR_ULTIMO: "FINANCEIRO_ASSINAR_ULTIMO",
  FINANCEIRO_LIQUIDAR_PAGAMENTO: "FINANCEIRO_LIQUIDAR_PAGAMENTO",
  FINANCEIRO_GERIR_TESOURARIA: "FINANCEIRO_GERIR_TESOURARIA",
  FINANCEIRO_GERIR_GATEWAYS: "FINANCEIRO_GERIR_GATEWAYS",
  FINANCEIRO_CONSULTAR_LEDGER: "FINANCEIRO_CONSULTAR_LEDGER",

  // Administrador Master
  ADMIN_ACESSO_TOTAL: "ADMIN_ACESSO_TOTAL"
} as const;

export function verificarPermissao(perfil: PerfilUsuario, permissaoNecessaria: string): boolean {
  if (perfil === "ADMINISTRADOR") return true;

  if (perfil === "PRODUTOR") {
    return [
      PERMISSOES.PRODUTOR_VER_PROPRIOS_DADOS,
      PERMISSOES.PRODUTOR_SOLICITAR_REPASSE,
      PERMISSOES.PRODUTOR_SOLICITAR_ANTECIPACAO,
      PERMISSOES.PRODUTOR_TRANSFERIR_SALDOS,
      PERMISSOES.PRODUTOR_ASSINAR_DIGITALMENTE
    ].includes(permissaoNecessaria as any);
  }

  if (perfil === "FINANCEIRO") {
    return [
      PERMISSOES.FINANCEIRO_VISAO_GLOBAL,
      PERMISSOES.FINANCEIRO_ANALISAR_OPERACAO,
      PERMISSOES.FINANCEIRO_APROVAR_REJEITAR,
      PERMISSOES.FINANCEIRO_ASSINAR_ULTIMO,
      PERMISSOES.FINANCEIRO_LIQUIDAR_PAGAMENTO,
      PERMISSOES.FINANCEIRO_GERIR_TESOURARIA,
      PERMISSOES.FINANCEIRO_GERIR_GATEWAYS,
      PERMISSOES.FINANCEIRO_CONSULTAR_LEDGER
    ].includes(permissaoNecessaria as any);
  }

  return false;
}
