import { formatCurrency } from '../../formatters.js';

function resolveRule(state, event) {
  if (state.resolveCommercialFeeRule) return state.resolveCommercialFeeRule({eventId:event.id, producerId:event.producerId, paymentMethod:'Cartão de Crédito'}).rule;
  const rules=(state.data.spreadRules||[]).filter(r=>r.status==='Ativa');
  return rules.find(r=>r.scopeType==='Evento'&&r.scopeId===event.id)||rules.find(r=>r.scopeType==='Produtor'&&r.scopeId===event.producerId)||rules.find(r=>r.scopeType==='Geral Disk')||null;
}
function apuracao(state){
  const events=state.data.events||[];
  const rows=events.map(e=>{
    const rule=resolveRule(state,e)||{}; const gross=Number(e.grossSales||0); const charged=Number(rule.chargedRate||0); const mdr=Number(rule.mdr||0); const fixed=Number(rule.fixedFee||0); const additional=Number(rule.additionalCost||0); const tx=Math.max(1,Number(e.soldTickets||1));
    const commercial=gross*charged/100; const mdrCost=gross*mdr/100; const fixedCost=tx*fixed; const additionalCost=gross*additional/100; const margin=commercial-mdrCost-fixedCost-additionalCost;
    return {event:e,rule,gross,commercial,mdrCost,fixedCost,additionalCost,margin,spread:charged-mdr};
  });
  return {rows, totals:rows.reduce((a,r)=>({gross:a.gross+r.gross,commercial:a.commercial+r.commercial,mdrCost:a.mdrCost+r.mdrCost,fixedCost:a.fixedCost+r.fixedCost,additionalCost:a.additionalCost+r.additionalCost,margin:a.margin+r.margin}),{gross:0,commercial:0,mdrCost:0,fixedCost:0,additionalCost:0,margin:0})};
}
export function renderDiskControladoria(state, secao='visao') {
  const a=apuracao(state); const produtor=state.data?.producer?.name||'Todos os produtores'; const evento=state.data?.bordero?.eventName||'Todos os eventos';
  return `<div class="limitless-page-header"><div class="breadcrumbs"><span>Financeiro Disk</span><span class="breadcrumb-separator">/</span><span class="breadcrumb-active">Controladoria</span></div><div class="page-title-row"><div class="page-title-group"><h1><i class="ph-chart-line-up"></i> Controladoria Financeira</h1><p class="page-title-desc">DRE e rentabilidade alimentados pela mesma matriz vigente de MDR, Spread e Regras Comerciais.</p></div><div class="header-action-group"><button class="btn btn-secondary" onclick="window.print()"><i class="ph-download-simple"></i> Exportar</button></div></div></div><div class="limitless-content"><div class="alert alert-primary border-0 mb-3"><strong>Contexto administrativo:</strong> ${produtor} • ${evento}. Valores de MDR, spread e margem são internos do Financeiro Disk.</div><div class="d-flex gap-2 flex-wrap mb-4">${tab('diskControladoria','Visão Geral',secao==='visao')}${tab('diskCentrosCustos','Centros de Custos',secao==='centros')}${tab('diskOrcamentos','Orçamentos',secao==='orcamentos')}${tab('diskDre','DRE Gerencial',secao==='dre')}${tab('diskRentabilidade','Rentabilidade',secao==='rentabilidade')}${tab('diskProjecoes','Projeções',secao==='projecoes')}</div>${renderSecao(secao,a)}</div>`;
}
function tab(v,l,a){return `<button class="btn ${a?'btn-primary':'btn-secondary'} btn-sm" onclick="window.app.navigate('${v}')">${l}</button>`}
function renderSecao(s,a){if(s==='dre')return dre(a);if(s==='rentabilidade')return rentabilidade(a);if(s==='centros')return painel('Centros de Custos','<div class="card-body"><div class="alert alert-info mb-0">Centros de custos preservados. A apuração de adquirência agora vem da matriz MDR/Spread.</div></div>');if(s==='orcamentos')return painel('Controle Orçamentário','<div class="card-body"><div class="alert alert-warning mb-0">Orçamentos preservados e independentes do Ledger realizado.</div></div>');if(s==='projecoes')return painel('Projeção de Caixa','<div class="card-body"><div class="alert alert-primary mb-0">Projeções não alteram o Ledger nem a apuração realizada.</div></div>');return visao(a)}
function kpis(a){const t=a.totals;const pct=t.gross?t.margin/t.gross*100:0;return `<div class="row g-3 mb-4">${kpi('Vendas brutas apuradas',formatCurrency(t.gross),'ph-trend-up')}${kpi('Receita comercial Disk',formatCurrency(t.commercial),'ph-receipt')}${kpi('MDR / adquirência',formatCurrency(t.mdrCost),'ph-credit-card')}${kpi('Margem de taxas',formatCurrency(t.margin),'ph-chart-line-up')}${kpi('Margem sobre vendas',pct.toFixed(2).replace('.',',')+'%','ph-percent')}</div>`}
function visao(a){return `${kpis(a)}${painel('Apuração por Evento', tabela(a))}<div class="alert alert-success mt-3"><strong>V0.6.2:</strong> Regra comercial resolvida na hierarquia Evento → Produtor → Geral Disk. A mesma apuração alimenta Rentabilidade e DRE Gerencial.</div>`}
function dre(a){const t=a.totals;return `${kpis(a)}${painel('DRE Gerencial — Taxas e Adquirência',`<div class="card-body"><div style="max-width:820px">${dreL('Receita comercial de taxas',t.commercial)}${dreL('(-) MDR / custos de adquirência',-t.mdrCost)}${dreL('(-) Tarifas fixas transacionais',-t.fixedCost)}${dreL('(-) Custos adicionais parametrizados',-t.additionalCost)}${dreL('Margem líquida de taxas / spread',t.margin,true)}</div></div>`)}<div class="alert alert-info mt-3"><strong>DRE Gerencial:</strong> apuração administrativa baseada nas regras comerciais vigentes; não substitui escrituração contábil/fiscal oficial.</div>`}
function rentabilidade(a){return `${kpis(a)}${painel('Rentabilidade por Evento — MDR, Spread e Margem',tabela(a))}`}
function tabela(a){return `<div class="card-body card-body-no-padding"><table class="limitless-table"><thead><tr><th>Evento</th><th>Regra aplicada</th><th>Vendas</th><th>Taxa</th><th>MDR</th><th>Spread</th><th>Receita Disk</th><th>Custo adquirência</th><th>Margem líquida</th></tr></thead><tbody>${a.rows.map(r=>`<tr><td><strong>${r.event.name}</strong><div class="text-muted fs-xxs">${r.event.producerName||r.event.producerId}</div></td><td>${r.rule.name||'Sem regra'}<div class="text-muted fs-xxs">${r.rule.scopeType||'—'} · v${r.rule.version||1}</div></td><td>${formatCurrency(r.gross)}</td><td>${Number(r.rule.chargedRate||0).toFixed(2)}%</td><td>${Number(r.rule.mdr||0).toFixed(2)}%</td><td><span class="badge badge-success">+${r.spread.toFixed(2)}%</span></td><td>${formatCurrency(r.commercial)}</td><td>${formatCurrency(r.mdrCost+r.fixedCost+r.additionalCost)}</td><td><strong>${formatCurrency(r.margin)}</strong></td></tr>`).join('')}</tbody></table></div>`}
function kpi(t,v,i){return `<div class="col"><div class="card-panel h-100"><div class="card-body"><div class="d-flex gap-2 align-items-center text-muted fs-xs"><i class="${i} fs-4"></i>${t}</div><div class="fs-4 fw-bold mt-2">${v}</div></div></div></div>`}
function painel(t,b){return `<div class="card-panel"><div class="card-header-bar"><div class="card-title-group"><h2>${t}</h2></div></div>${b}</div>`}
function dreL(n,v,total=false){return `<div style="display:flex;justify-content:space-between;padding:11px 0;border-bottom:1px solid var(--border-color);${total?'font-size:1.08rem':''}"><span class="${total?'fw-bold':''}">${n}</span><strong>${formatCurrency(v)}</strong></div>`}
