function money(v){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v)}
function badge(s){return `<span class="badge badge-${s==='Conciliado'?'success':s==='Divergência'?'danger':s==='Resolvida'?'info':'warning'}">${s}</span>`}
export function renderDiskConciliacao(state){
 const stored=state.data.reconciliationItems||[]; const itens=stored.length?stored:[{id:'CON-001',camada:'Adquirentes',origem:'Adquirente → Recebível',ref:'LIQ-20260929-0182',produtor:'Produtora ABC',evento:'Festival de Verão',esperado:184520,realizado:184520,status:'Conciliado'},{id:'CON-002',camada:'Gateways',origem:'Gateway → Adquirente',ref:'GTW-20260929-7710',produtor:'Produtora XYZ',evento:'Arena Music',esperado:96340.5,realizado:96340.5,status:'Conciliado'},{id:'CON-003',camada:'PIX/CNAB',origem:'Banco → PIX',ref:'PIX-20260929-4412',produtor:'Produtora ABC',evento:'Festival de Verão',esperado:48200,realizado:48150,status:'Divergência'},{id:'CON-004',camada:'Repasses',origem:'Repasse → Banco',ref:'REP-000128',produtor:'Produtora ABC',evento:'Festival de Verão',esperado:50000,realizado:50000,status:'Em análise'}];
 const div=itens.filter(i=>i.status==='Divergência'), ok=itens.filter(i=>i.status==='Conciliado'), diff=itens.reduce((s,i)=>s+(i.realizado-i.esperado),0), total=itens.reduce((s,i)=>s+i.esperado,0);
 return `<div class="limitless-content"><div class="p13-head"><div><h2><i class="ph-arrows-left-right"></i> Central de Conciliação Financeira</h2><p>Banco × PIX/CNAB × Gateway × Adquirente × Recebível × Repasse × Ledger.</p></div><div class="p13-actions"><button class="btn btn-light" onclick="window.app.p19ConcFilter('')">Todas</button><button class="btn btn-primary" onclick="window.app.p19ConcFilter('Divergência')">Divergências</button></div></div>
 <div class="kpi-grid"><div class="kpi-card highlight"><div class="kpi-header"><span class="kpi-title">Volume analisado</span></div><div class="kpi-value">${money(total)}</div></div><div class="kpi-card success-accent"><div class="kpi-header"><span class="kpi-title">Conciliados</span></div><div class="kpi-value">${ok.length}</div></div><div class="kpi-card"><div class="kpi-header"><span class="kpi-title">Divergências abertas</span></div><div class="kpi-value">${div.length}</div></div><div class="kpi-card"><div class="kpi-header"><span class="kpi-title">Diferença líquida</span></div><div class="kpi-value">${money(diff)}</div><div class="kpi-subtext">Sem ajuste automático</div></div></div>
 <div class="card-panel mb-3"><div class="card-body"><div class="row g-2">${['Bancária','PIX/CNAB','Gateways','Adquirentes','Recebíveis','Repasses','Ledger'].map((x,i)=>`<div class="col-6 col-md"><button class="btn btn-light w-100 text-start" onclick="window.app.p19ConcLayer('${x}')"><span class="fs-xxs text-muted">${i+1}. CAMADA</span><br><strong>${x}</strong></button></div>`).join('')}</div></div></div>
 <div class="card-panel"><div class="card-header-bar"><div class="card-title-group"><h2>Itens de Conciliação</h2><p class="card-subtitle">Divergência permanece aberta até causa, evidência, responsável e ação corretiva.</p></div></div><div class="card-body card-body-no-padding"><div class="table-responsive"><table class="limitless-table" id="p19ConcTable"><thead><tr><th>Camada / Origem</th><th>Referência</th><th>Produtor / Evento</th><th>Esperado</th><th>Realizado</th><th>Diferença</th><th>Status</th><th>Ação</th></tr></thead><tbody>${itens.map(i=>`<tr data-layer="${i.camada}" data-status="${i.status}"><td><strong>${i.camada}</strong><div class="text-muted fs-xs">${i.origem}</div></td><td>${i.ref}</td><td>${i.produtor}<div class="text-muted fs-xs">${i.evento}</div></td><td>${money(i.esperado)}</td><td>${money(i.realizado)}</td><td class="${i.realizado!==i.esperado?'text-danger fw-bold':''}">${money(i.realizado-i.esperado)}</td><td>${badge(i.status)}</td><td>${i.status==='Divergência'?`<button class="btn btn-sm btn-primary" onclick="window.app.p19Investigate('${i.id}')">Investigar</button>`:`<button class="btn btn-sm btn-light" onclick="window.app.p19ConcDetail('${i.id}')">Detalhes</button>`}</td></tr>`).join('')}</tbody></table></div></div></div></div>`;
}
