const money = (v) => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v);

export function renderDiskAssinaturasIntegracoes(state, section='assinaturas') {
  const tabs = [
    ['assinaturas','Central de Assinaturas','ph-signature'],
    ['documentos','Documentos','ph-files'],
    ['autentique','Autentique','ph-seal-check'],
    ['contaazul','Conta Azul','ph-arrows-clockwise'],
    ['sincronizacoes','Sincronizações','ph-git-merge'],
    ['logs','Logs','ph-terminal-window']
  ];
  const tabbar = `<div class="d-flex flex-wrap gap-2 mb-4">${tabs.map(([id,label,icon])=>`<button class="btn ${section===id?'btn-primary':'btn-light'}" onclick="window.app.navigate('diskIntegracao_${id}')"><i class="${icon} me-1"></i>${label}</button>`).join('')}</div>`;
  return `<div class="content-wrapper"><div class="content-inner"><div class="content px-0">${tabbar}${body(section,state)}</div></div></div>`;
}

function body(section,state){
  if(section==='autentique') return autentique();
  if(section==='contaazul') return contaAzul();
  if(section==='sincronizacoes') return sincronizacoes();
  if(section==='logs') return logs();
  if(section==='documentos') return documentos();
  return assinaturas();
}

function kpi(title,value,sub,icon){return `<div class="col-sm-6 col-xl-3"><div class="card"><div class="card-body"><div class="d-flex align-items-center"><i class="${icon} fs-2 me-3"></i><div><div class="text-muted fs-sm">${title}</div><div class="fs-3 fw-semibold">${value}</div><div class="text-muted fs-sm">${sub}</div></div></div></div></div></div>`}

function assinaturas(){return `
<div class="mb-3"><h4 class="mb-1">Central de Assinaturas</h4><div class="text-muted">Documentos financeiros com ordem obrigatória: Produtor primeiro e Financeiro Disk por último.</div></div>
<div class="row">${kpi('Aguardando Produtor','8','assinaturas pendentes','ph-user-circle')}${kpi('Aguardando Financeiro Disk','6','liberadas após produtor','ph-bank')}${kpi('Concluídos','96','documentos assinados','ph-check-circle')}${kpi('Com ocorrência','5','recusados, expirados ou erro','ph-warning-circle')}</div>
<div class="card"><div class="card-header d-flex align-items-center"><h5 class="mb-0">Esteira de assinaturas</h5><span class="badge bg-primary ms-auto">Autentique</span></div><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Documento</th><th>Tipo</th><th>Produtor</th><th>Evento</th><th>Valor</th><th>Status</th><th>Próxima ação</th></tr></thead><tbody>
<tr><td>REP-00281</td><td>Repasse</td><td>ABC Eventos</td><td>Festival X</td><td>${money(180000)}</td><td><span class="badge bg-warning text-dark">Aguardando Produtor</span></td><td>Produtor assinar</td></tr>
<tr><td>BOR-00128</td><td>Borderô</td><td>XYZ Produções</td><td>Evento Y</td><td>${money(428500)}</td><td><span class="badge bg-info">Aguardando Disk</span></td><td>Assinatura final Disk</td></tr>
<tr><td>ANT-00042</td><td>Antecipação</td><td>ABC Eventos</td><td>Festival X</td><td>${money(95000)}</td><td><span class="badge bg-success">Concluído</span></td><td>Documento arquivado</td></tr>
</tbody></table></div></div>
<div class="alert alert-info"><strong>Regra de governança:</strong> a assinatura do Financeiro Disk permanece bloqueada até a confirmação da assinatura do Produtor. A conclusão do documento libera a próxima etapa do workflow financeiro.</div>`}

function documentos(){return `<div class="mb-3"><h4 class="mb-1">Documentos para Assinatura</h4><div class="text-muted">Modelos e documentos vinculados a repasses, antecipações, borderôs, contratos e demais operações financeiras.</div></div>
<div class="row"><div class="col-lg-8"><div class="card"><div class="card-header"><h5 class="mb-0">Documentos</h5></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Modelo</th><th>Uso</th><th>Ordem</th><th>Provedor</th><th>Situação</th></tr></thead><tbody><tr><td>Termo de Repasse</td><td>Repasses aprovados</td><td>Produtor → Disk</td><td>Autentique</td><td><span class="badge bg-success">Ativo</span></td></tr><tr><td>Termo de Antecipação</td><td>Antecipações aprovadas</td><td>Produtor → Disk</td><td>Autentique</td><td><span class="badge bg-success">Ativo</span></td></tr><tr><td>Borderô Definitivo</td><td>Fechamento de evento</td><td>Produtor → Disk</td><td>Autentique</td><td><span class="badge bg-success">Ativo</span></td></tr></tbody></table></div></div></div><div class="col-lg-4"><div class="card"><div class="card-body"><h5>Novo documento</h5><p class="text-muted">O documento deve nascer de uma operação aprovada ou de um modelo autorizado.</p><button class="btn btn-primary w-100" onclick="window.app.showToast('Fluxo preparado para criação via API Autentique.','info')"><i class="ph-plus me-1"></i>Criar documento</button></div></div></div></div>`}

function autentique(){return `<div class="mb-3"><h4 class="mb-1">Integração Autentique</h4><div class="text-muted">Motor externo de assinatura digital do Módulo Financeiro V1.</div></div>
<div class="row">${kpi('Conexão','Preparada','aguardando credencial de produção','ph-plugs-connected')}${kpi('Webhooks','Configuráveis','atualização automática de status','ph-webhooks-logo')}${kpi('Ordem padrão','Produtor → Disk','Disk sempre por último','ph-list-numbers')}${kpi('Ambiente','Homologação','separado de produção','ph-test-tube')}</div>
<div class="row"><div class="col-lg-7"><div class="card"><div class="card-header"><h5 class="mb-0">Configuração</h5></div><div class="card-body"><div class="mb-3"><label class="form-label">Ambiente</label><select class="form-select"><option>Homologação</option><option>Produção</option></select></div><div class="mb-3"><label class="form-label">Token/API</label><input class="form-control" type="password" value="credencial-nao-exposta" disabled></div><div class="mb-3"><label class="form-label">Webhook de retorno</label><input class="form-control" value="/api/integracoes/autentique/webhook" readonly></div><button class="btn btn-primary" onclick="window.app.showToast('Teste de conexão preparado. Conecte a credencial real no backend.','info')">Testar conexão</button></div></div></div><div class="col-lg-5"><div class="card"><div class="card-header"><h5 class="mb-0">Eventos tratados</h5></div><div class="card-body"><ul class="mb-0"><li>Documento criado/enviado</li><li>Produtor assinou</li><li>Financeiro Disk assinou</li><li>Documento concluído</li><li>Recusa/cancelamento</li><li>Erro de integração</li></ul></div></div></div></div>
<div class="alert alert-warning"><strong>Segurança:</strong> tokens e segredos não são armazenados no frontend. A conexão real deve ocorrer exclusivamente pelo backend.</div>`}

function contaAzul(){return `<div class="mb-3"><h4 class="mb-1">Integração Conta Azul</h4><div class="text-muted">Sincronização controlada com o ERP utilizado pela Disk, sem substituir o Core Financeiro.</div></div>
<div class="row">${kpi('Conexão','OAuth 2.0','autorização sem senha no módulo','ph-key')}${kpi('Sincronizações','6 áreas','mapeamentos independentes','ph-arrows-clockwise')}${kpi('Pendências','4','aguardando tratamento','ph-hourglass')}${kpi('Erros','1','sem sucesso silencioso','ph-warning')}</div>
<div class="card"><div class="card-header d-flex align-items-center"><h5 class="mb-0">Mapa de responsabilidade dos dados</h5><button class="btn btn-primary btn-sm ms-auto" onclick="window.app.showToast('Fluxo OAuth preparado. A conexão real requer Client ID/Secret no backend.','info')"><i class="ph-plugs-connected me-1"></i>Conectar Conta Azul</button></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Informação</th><th>Fonte principal</th><th>Direção</th><th>Política</th></tr></thead><tbody><tr><td>Produtor / Evento</td><td>Financeiro V1 / Core</td><td>V1 → Conta Azul</td><td>Não sobrescrever origem</td></tr><tr><td>Saldo / Repasse / Antecipação</td><td>Financeiro V1</td><td>Interno</td><td>Não delegar ao ERP</td></tr><tr><td>Fornecedores</td><td>Mapeável</td><td>Bidirecional controlada</td><td>Resolver conflito</td></tr><tr><td>Contas a Pagar</td><td>Configurável</td><td>V1 ↔ Conta Azul</td><td>Idempotência obrigatória</td></tr><tr><td>Contas a Receber</td><td>Configurável</td><td>V1 ↔ Conta Azul</td><td>Idempotência obrigatória</td></tr><tr><td>Pagamento confirmado</td><td>Banco / Financeiro V1</td><td>V1 → Conta Azul</td><td>Após conciliação</td></tr></tbody></table></div></div>
<div class="alert alert-info"><strong>Princípio:</strong> Conta Azul atua como integração ERP. Ledger, saldo por evento, regras de repasse, MDR e workflows permanecem sob responsabilidade do Módulo Financeiro V1.</div>`}

function sincronizacoes(){return `<div class="mb-3"><h4 class="mb-1">Central de Sincronizações</h4><div class="text-muted">Fila única para Autentique e Conta Azul, com idempotência, tentativa, retorno e tratamento de divergências.</div></div><div class="card"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Data</th><th>Origem</th><th>Destino</th><th>Registro</th><th>Tipo</th><th>Status</th><th>Ação</th></tr></thead><tbody><tr><td>29/09 08:41</td><td>Financeiro V1</td><td>Autentique</td><td>REP-00281</td><td>Documento</td><td><span class="badge bg-success">Sincronizado</span></td><td>Detalhes</td></tr><tr><td>29/09 08:42</td><td>Financeiro V1</td><td>Conta Azul</td><td>CP-01882</td><td>Conta a pagar</td><td><span class="badge bg-success">Sincronizado</span></td><td>Detalhes</td></tr><tr><td>29/09 08:43</td><td>Conta Azul</td><td>Financeiro V1</td><td>FOR-00128</td><td>Fornecedor</td><td><span class="badge bg-warning text-dark">Divergente</span></td><td><button class="btn btn-sm btn-light">Resolver</button></td></tr><tr><td>29/09 08:44</td><td>Financeiro V1</td><td>Conta Azul</td><td>CR-00891</td><td>Conta a receber</td><td><span class="badge bg-danger">Erro</span></td><td><button class="btn btn-sm btn-light">Reprocessar</button></td></tr></tbody></table></div></div>`}

function logs(){return `<div class="mb-3"><h4 class="mb-1">Logs de Integração</h4><div class="text-muted">Rastreabilidade técnica sem exposição de tokens, senhas ou dados secretos.</div></div><div class="card"><div class="card-body font-monospace fs-sm"><div>08:44:12 CONTA_AZUL sync CR-00891 → ERRO_VALIDACAO</div><div>08:43:50 CONTA_AZUL fornecedor FOR-00128 → DIVERGENTE</div><div>08:42:31 CONTA_AZUL CP-01882 → SINCRONIZADO</div><div>08:41:07 AUTENTIQUE REP-00281 → DOCUMENTO_ENVIADO</div><div>08:40:58 AUTENTIQUE webhook → VALIDADO</div></div></div><div class="alert alert-secondary">Logs operacionais devem registrar correlação, usuário, horário, origem, destino e resultado. Segredos de autenticação nunca devem aparecer no log.</div>`}
