/** Pacote 18 — Central Operacional de Gateways e Adquirentes */
import { formatCurrency } from '../../formatters.js';

const tabs=[['config','Configurações'],['credenciais','Credenciais'],['cartoes','Bandeiras e Cartões'],['pix','PIX'],['boleto','Boletos'],['parcelamento','Parcelamento'],['antifraude','Antifraude'],['webhooks','Webhooks'],['conciliacao','Conciliação'],['estornos','Estornos'],['logs','Logs'],['relatorios','Relatórios']];
export function renderDiskGateways(state){
 const gs=state.data.gatewayConfigs||[], raw=state.data.gateways||[]; const active=gs.filter(x=>x.enabled).length; const vol=raw.reduce((a,b)=>a+(b.totalVolumeProcessed||0),0);
 return `<div class="limitless-page-header" style="background:#0f172a;color:white;border-bottom:2px solid #3b82f6"><div class="breadcrumbs" style="color:#94a3b8">Financeiro Disk / Gateways e Adquirentes</div><div class="page-title-row"><div class="page-title-group"><h1 style="color:#f8fafc"><i class="ph-cpu"></i> Central Operacional de Gateways e Adquirentes</h1><p class="page-title-desc" style="color:#94a3b8">Infraestrutura de pagamento, credenciais, meios aceitos, custos reais, segurança e operação.</p></div><button class="btn btn-primary" onclick="window.app.p18Action('novo')"><i class="ph-plus"></i> Novo Gateway</button></div></div>
 <div class="limitless-content"><div class="info-banner info-banner-amber"><i class="ph-shield-warning"></i><div><strong>Exclusivo Financeiro Disk.</strong> Credenciais nunca são exibidas em texto aberto. Testes externos só serão confirmados quando houver backend e integração homologada.</div></div>
 <div class="row g-3 mb-4">${kpi('Gateways ativos',active,'ph-check-circle')}${kpi('Volume processado',formatCurrency(vol),'ph-chart-line-up')}${kpi('Produção',gs.filter(x=>x.environment==='Produção').length,'ph-cloud-check')}${kpi('Pendentes de integração',gs.filter(x=>x.connectionStatus==='Não configurado').length,'ph-warning')}</div>
 <div class="card-panel mb-4"><div class="card-body"><div class="d-flex gap-2 flex-wrap">${tabs.map(([id,n],i)=>`<button class="btn ${i===0?'btn-primary':'btn-light'} btn-sm" onclick="window.app.p18Tab('${id}',this)">${n}</button>`).join('')}</div></div></div>
 <div id="p18-tab-content">${renderConfig(gs,raw)}</div></div>`;
}
function renderConfig(gs,raw){return `<div class="card-panel"><div class="card-header-bar"><div class="card-title-group"><h2>Gateways configurados</h2><p class="card-subtitle">Cadastro, ambiente, disponibilidade e vínculo com Taxas/MDR.</p></div></div><div class="table-responsive"><table class="limitless-table"><thead><tr><th>Gateway</th><th>Ambiente</th><th>Conexão</th><th>Cartões</th><th>PIX</th><th>Boleto</th><th>Situação</th><th>Ações</th></tr></thead><tbody>${gs.map(g=>`<tr><td><strong>${g.name}</strong><div class="text-muted fs-xs">${g.id}</div></td><td><span class="badge ${g.environment==='Produção'?'badge-success':'badge-warning'}">${g.environment}</span></td><td>${g.connectionStatus}</td><td>${(g.cards||[]).join(', ')||'—'}</td><td>${g.pix?.enabled?'Ativo':'Inativo'}</td><td>${g.boleto?.enabled?'Ativo':'Inativo'}</td><td><span class="badge ${g.enabled?'badge-success':'badge-secondary'}">${g.enabled?'Ativo':'Inativo'}</span></td><td><div class="d-flex gap-1 flex-wrap"><button class="btn btn-sm btn-light" onclick="window.app.p18Action('editar','${g.id}')">Editar</button><button class="btn btn-sm btn-light" onclick="window.app.p18Action('testar','${g.id}')">Testar</button><button class="btn btn-sm btn-light" onclick="window.app.p18Action('status','${g.id}')">${g.enabled?'Inativar':'Ativar'}</button><button class="btn btn-sm btn-light" onclick="window.app.p18Action('logs','${g.id}')">Logs</button></div></td></tr>`).join('')}</tbody></table></div><div class="p-3 border-top d-flex gap-2"><button class="btn btn-primary" onclick="window.app.navigate('taxas')"><i class="ph-percent"></i> Taxas e Regras Comerciais</button><button class="btn btn-light" onclick="window.app.navigate('diskConciliacao')">Abrir Conciliação</button></div></div>`}
export function renderGatewayTab(state,tab){const gs=state.data.gatewayConfigs||[]; const cards={credenciais:['Credenciais','Merchant ID, Client ID e segredo são mascarados.','cred'],cartoes:['Bandeiras e Cartões','Defina bandeiras aceitas por gateway.','cards'],pix:['PIX','Disponibilidade, chave operacional e prazo de liquidação.','pix'],boleto:['Boletos','Banco, carteira, convênio e parâmetros de cobrança.','boleto'],parcelamento:['Parcelamento','Máximo de parcelas e início de juros.','installments'],antifraude:['Antifraude','Provedor e ativação da camada antifraude.','antifraud'],webhooks:['Webhooks','Recebimento de eventos de pagamento e liquidação.','webhooks']}; if(tab==='config') return renderConfig(gs,state.data.gateways||[]); if(cards[tab]){const [t,s,key]=cards[tab];return section(t,s,gs.map(g=>gatewayCard(g,key)).join(''));} if(tab==='conciliacao') return section('Conciliação','A operação continua na Central de Conciliação.',`<div class="p-4"><p>Gateway → recebível → liquidação → banco → Ledger.</p><button class="btn btn-primary" onclick="window.app.navigate('diskConciliacao')">Abrir Conciliação</button></div>`); if(tab==='estornos') return section('Estornos','Estornos e chargebacks preservam o vínculo com a transação original.',`<div class="p-4"><button class="btn btn-primary" onclick="window.app.navigate('estornos')">Abrir Central de Estornos</button></div>`); if(tab==='logs') return section('Logs','Auditoria local das configurações.',gs.map(g=>`<div class="p-3 border-bottom"><strong>${g.name}</strong>${(g.logs||[]).slice(0,5).map(l=>`<div class="text-muted fs-sm mt-1">${l.at} · ${l.action} · ${l.actor}${l.result?' · '+l.result:''}</div>`).join('')||'<div class="text-muted fs-sm">Sem eventos.</div>'}</div>`).join('')); return section('Relatórios','Resumo operacional por gateway.',`<div class="p-4"><div class="row g-3">${gs.map(g=>`<div class="col-md-6"><div class="border rounded p-3"><strong>${g.name}</strong><div class="text-muted fs-sm">${g.environment} · ${g.enabled?'Ativo':'Inativo'} · ${g.connectionStatus}</div></div></div>`).join('')}</div></div>`);}
function gatewayCard(g,key){let value=''; if(key==='cred') value=`Merchant: ${g.merchantId||'Não informado'} · Client: ${g.clientId||'Não informado'} · Secret: ${g.secretConfigured?'CONFIGURADO':'NÃO CONFIGURADO'}`; else if(key==='cards') value=(g.cards||[]).join(', ')||'Nenhuma bandeira'; else {const o=g[key]||{}; value=Object.entries(o).map(([k,v])=>`${k}: ${typeof v==='boolean'?(v?'Sim':'Não'):v}`).join(' · ')||'Não configurado';} return `<div class="p-3 border-bottom d-flex justify-content-between gap-3 align-items-center"><div><strong>${g.name}</strong><div class="text-muted fs-sm mt-1">${value}</div></div><button class="btn btn-sm btn-light" onclick="window.app.p18Action('configurar-${key}','${g.id}')">Configurar</button></div>`}
function section(t,s,b){return `<div class="card-panel"><div class="card-header-bar"><div class="card-title-group"><h2>${t}</h2><p class="card-subtitle">${s}</p></div></div><div>${b}</div></div>`} function kpi(t,v,i){return `<div class="col-12 col-md-6 col-xl-3"><div class="card-panel h-100"><div class="card-body d-flex justify-content-between"><div><div class="text-muted fs-sm">${t}</div><div class="fs-3 fw-bold mt-1">${v}</div></div><i class="${i} fs-2 text-primary"></i></div></div></div>`}
